// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SchulbibliothekAP14.Migrations
{
    [DbContext(typeof(SchulbibliothekContext))]
    [Migration("20260904105736_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchulbibliothekAP14.Models.Buch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buch");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bild")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IstAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonenTypId")
                        .HasColumnType("int");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonenTypId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.PersonenTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonenTyp");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Transaktion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bemerkung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BuchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("TransaktionTypId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuchId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TransaktionTypId");

                    b.ToTable("Transaktion");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.TransaktionTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransaktionTyp");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Person", b =>
                {
                    b.HasOne("SchulbibliothekAP14.Models.PersonenTyp", "PersonenTyp")
                        .WithMany("Personen")
                        .HasForeignKey("PersonenTypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonenTyp");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Transaktion", b =>
                {
                    b.HasOne("SchulbibliothekAP14.Models.Buch", "Buch")
                        .WithMany("Transaktionen")
                        .HasForeignKey("BuchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchulbibliothekAP14.Models.Person", "Person")
                        .WithMany("Transaktionen")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchulbibliothekAP14.Models.TransaktionTyp", "TransaktionTyp")
                        .WithMany("Transaktionen")
                        .HasForeignKey("TransaktionTypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buch");

                    b.Navigation("Person");

                    b.Navigation("TransaktionTyp");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Buch", b =>
                {
                    b.Navigation("Transaktionen");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.Person", b =>
                {
                    b.Navigation("Transaktionen");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.PersonenTyp", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("SchulbibliothekAP14.Models.TransaktionTyp", b =>
                {
                    b.Navigation("Transaktionen");
                });
#pragma warning restore 612, 618
        }
    }
}
